name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: "Wocn10"
          outputs: snake.svg?palette=github-dark

      - name: Push snake.svg to main branch
        uses: EndBug/add-and-commit@v9
        with:
          add: snake.svg
          message: "Update snake.svg"
          branch: main